import Head from 'next/head';
import { PropsWithChildren } from 'react';
import GlobalStyles from '../../pages/styles/GlobalStyleds';
import Container from './Container';
import Footer from './Footer';
import Header from './Header';
export default function Layout({ children }: PropsWithChildren<any>) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <GlobalStyles />
      <Container>
        <Header />
        <main>{children}</main>
        <Footer />
      </Container>
    </>
  );
}
